name: Log Analyzer Workflow

on:
  push:
    branches:
      - prototype


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return black isort mypy

      - name: Run linters
        run: |
          black --check --line-length=79 .
          isort --check --profile black .

      - name: Run mypy
        run: |
          mypy --explicit-package-bases --ignore-missing-imports .

      - name: Test with flake8
        run: |
          python -m flake8

  test:
    runs-on: ubuntu-latest
    name: Test code
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest pytest
