name: Log Analyzer Workflow

on:
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PEP8 check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return black isort mypy

      - name: Run linters
        run: |
          black --check --line-length=79 .
          isort --check-only .

      - name: Run mypy
        run: |
          mypy .

      - name: Test with flake8
        run: |
          python -m flake8

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest pytest
